name: Wheresrhys
markdown: redcarpet
pygments: true
exclude: ['node_modules', 'grunt', 'Gruntfile.js', 'wheresrhys.sublime-*', 'package.json', '*.scss']
include: ['favicon.ico']
paginate: 1
paginate_path: "articles/page:num"